[workspace]
authors = ["Yixiang Gao <yixiangg310573@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "tinyrender"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=25.6.0.dev2025090305,<26"
